### PR TITLE
feat: add krzysztofzuraw.com

### PR DESCRIPTION
**Pull request by krzysztofzuraw**

### CODE REVIEW

**Comment by markodenic** [comment]
Hi, @krzysztofzuraw. Please put your data at a random position in the file. Thanks!

**Comment by krzysztofzuraw** [comment]
@markodenic done 😄

**Comment by naresh-io** [comment]
> @markodenic done 😄

@krzysztofzuraw please resolve the merge conflicts

**Comment by krzysztofzuraw** [comment]
@naresh-io fixed as well

**Pull request merged**
