### PR TITLE
Rishi added his blog

### PR DESCRIPTION
**Pull request by rishimohan**
Added rishimohan.me, I write about Next.js, Tailwind, React and building apps with these.

### CODE REVIEW

**Comment by markodenic** [comment]
Hi, @rishimohan. Please adjust the link, so it points directly to your blog. Thanks!

**Comment by rishimohan** [comment]
@markodenic Done :)

**Comment by markodenic** [comment]
Thanks, @rishimohan. Sorry, just another small adjustment. Can you, please, put the data at a random position in the file?

**Comment by rishimohan** [comment]
@markodenic No issues, done :)

**Review by markodenic — APPROVED** [review]

**Pull request merged**
