### PR TITLE
Add Stefan Baumgartner's blog

### PR DESCRIPTION
**Pull request by andi1984**
Adding here Stefan's blog fettblog.eu which is IMHO a go-to resource for
TypeScript and Rust lately.

### CODE REVIEW

**Comment by andi1984** [comment]
@ddprrt FYI. I hope this is fine for you?

**Comment by ddprrt** [comment]
I feel flattered! :)

**Comment by markodenic** [comment]
@andi1984 Can you please adjust the link, so it points directly to the blog? And, also put the data at a random position in the file.

@ddprrt, I attended one of your conferences in Linz. :)

**Comment by andi1984** [comment]
@markodenic Sure, will do in a minute

**Comment by andi1984** [comment]
@ddprrt @markodenic I linked it now directly to https://fettblog.eu/articles/

**Comment by markodenic** [comment]
@andi1984 Please put the data at a random position in the file. Thanks!

**Comment by andi1984** [comment]
@markodenic Okay, I just moved it a few records up. 👍🏼

**Review by markodenic — APPROVED** [review]

**Pull request merged**
