### PR TITLE
Add zachjonesnoel blog

### PR DESCRIPTION
**Pull request by zachjonesnoel**

### CODE REVIEW

**Comment by naresh-io** [comment]
@zachjonesnoel please fix the merge conflicts

**Review by zachjonesnoel — COMMENTED** [review]
Resolved the conflicts

**Comment by zachjonesnoel** [comment]
@naresh-io resolved the merge.

**Comment by naresh-io** [comment]
Hey @zachjonesnoel while resolving the conflicts, you removed other blog. Please fix it and test if possible.

**Pull request merged**
