### PR TITLE
Updated data.js

### PR DESCRIPTION
**Pull request by alkaguptaa**
Updated!
Added my own blogging website

### CODE REVIEW

**Comment by markodenic** [comment]
Hi, @alkaguptaa. Please put your data at a random position in the file. Thanks!

**Comment by alkaguptaa** [comment]
> Hi, @alkaguptaa. Please put your data at a random position in the file and update the title of the PR. Thanks!

Sure!

**Comment by naresh-io** [comment]
@alkaguptaa please resolve the merge conflicts

**Comment by alkaguptaa** [comment]
> @alkaguptaa please resolve the merge conflicts

Can you please assist me on how to resolve this?

**Comment by naresh-io** [comment]
> > @alkaguptaa please resolve the merge conflicts
> 
> Can you please assist me on how to resolve this?

Hey @alkaguptaa try this tutorial [https://www.youtube.com/watch?v=xNVM5UxlFSA](url) and let us know if you need further help.

**Comment by alkaguptaa** [comment]
> > > @alkaguptaa please resolve the merge conflicts
> > 
> > 
> > Can you please assist me on how to resolve this?
> 
> Hey @alkaguptaa try this tutorial [https://www.youtube.com/watch?v=xNVM5UxlFSA](url) and let us know if you need further help.

Sorry to inform you that the url is not working :(

**Comment by naresh-io** [comment]
> https://www.youtube.com/watch?v=xNVM5UxlFSA

Try [this link]([https://www.youtube.com/watch?v=xNVM5UxlFSA](https://github.com/markodenic/awesome-tech-blogs/pull/url))

**Pull request merged**
