### PR TITLE
Add Jiri Tichy Blog

### PR DESCRIPTION
**Pull request by jiritichy**
Happy to be listed on your website. :)

### CODE REVIEW

**Comment by MarkoDenic** [comment]
Hi Jiri. You're missing comas after every tag. Can you, please fix it?

Thanks!

**Comment by jiritichy** [comment]
Hi Marko, sorry for it. I just changed it.

Thanks!

**Review by MarkoDenic — APPROVED** [review]

**Comment by MarkoDenic** [comment]
No worries. Just another minor thing. You have a typo on line 90. Can you, please change "Infrastrucutre" to "Infrastructure"?

Thanks!

**Comment by jiritichy** [comment]
Done.

**Review by MarkoDenic — APPROVED** [review]

**Pull request merged**
