### PR TITLE
Added a blog

### PR DESCRIPTION
**Pull request by Aditid132**

### CODE REVIEW

**Comment by naresh-io** [comment]
@Aditid132 hey can you format it correctly and add the blog somewhere in between

**Comment by Aditid132** [comment]
> @Aditid132 hey can you format it correctly and add the blog somewhere in between

yeah sure will do

**Comment by AbbeyIT** [comment]
HI @Aditid132 Any updates on this pull request? Lmk if you need any help

**Comment by markodenic** [comment]
Closing this due to inactivity. @Aditid132 feel ree to open a new PR.

**Pull request closed without merging**
